[feat-3] Bot send messages
tavernadev/bot-discord pull request #7
Opened 2020-12-07 14:11 UTC by ItaloCanturil

### O que foi feito?
 - Comandos basicos para o bot falar
 - Comando basico do server

2020-12-07 15:14 UTC, saulonunesdev requested changes

2020-12-07 15:14 UTC, saulonunesdev commented on .gitignore
> +config.json
ao inves de usarmos config.json pra armazenar o token, vamos usar .env (dotenv) com ignore em arquivos .env

2020-12-07 15:14 UTC, saulonunesdev commented on .gitignore
> +config.json
https://www.npmjs.com/package/dotenv

2020-12-08 02:36 UTC, KastroWalker commented
@ItaloCanturil os arquivos estão com conflito, faz um pull na development, faz um merge com a branch [feat-3] resolve os conflitos e refaz o PR.

2020-12-10 17:34 UTC, ItaloCanturil commented
Antes de fazer o merge não será nescessario fazer os tests do JEST?

2020-12-19 21:58 UTC, closed without merging