[devops-11] Add codecov
tavernadev/bot-discord pull request #9
Opened 2020-12-09 04:57 UTC by bbruno001

**What was done?**
- install codecov 
- add codecov.yml
- edit test.yml

2020-12-09 05:26 UTC, bbruno001 commented
Need add "run: npm install codecov" on **test.yml** ??

2020-12-09 20:40 UTC, saulonunesdev commented
antes dessa atividade ser aprovada, é necessário aguardar a feat-5 #8  ser aprovada e mergeada na development

2020-12-13 08:04 UTC, saulonunesdev requested changes
@bbruno001 Favor resolver os conflitos

2020-12-17 00:45 UTC, saulonunesdev requested changes

2020-12-17 00:45 UTC, saulonunesdev commented on .github/workflows/test.yml
> +        run: npm test --coverage
o parametro --coverage não deve ser passado aki pois é um script npm, no caso só setar na configuração do jest **coverage: true**

2020-12-17 00:45 UTC, saulonunesdev commented on jest.config.js
> +  testMatch: ['**/tests/**/*.spec.js']
esse arquivo não está desatualizado? acredito q esses parametros já estão na branch develop.

no caso apenas o item **lcov** deve ser adicionado ao **coverageReporters** se necessário
Comparar com https://github.com/tavernadev/bot-discord/blob/development/jest.config.js

2020-12-17 00:45 UTC, saulonunesdev commented on package.json
> +  },
esses parametros estão redundantes, já existem no arquivo **jest.config.js**

2020-12-17 00:45 UTC, saulonunesdev commented on package.json
> +    "test:jest": "jest --coverage && codecov",
parametro --coverage já existe no arquivo **jest.config.js**
ao inves de adiconar **&& codecov**
criar instrução "codecov": "codecov"

e adiconar no CI após rodar o **npm test**

      - name: Run Codecov
        run: npm run codecov

2020-12-17 00:45 UTC, saulonunesdev commented on src/tests/example.spec.js
> +})
Esse arquivo está desatualizado

2020-12-19 21:46 UTC, saulonunesdev approved these changes

2020-12-19 21:47 UTC, merged

2020-12-19 23:58 UTC, saulonunesdev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[devops-11] - Adicionar Cobertura de Testes](https://trello.com/c/nZZBnsYi/16-devops-11-adicionar-cobertura-de-testes)